---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-deploy-test
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo-deploy-test

