---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-934b44f01008fd803b0875f09e6138ae
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/JamWils/podinfo-deploy.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/JamWils/podinfo-deploy.git
